In [2]:
import pandas as pd

# Load dataset
dataset = pd.read_csv('datasets/new_dataset_covertype.csv')
# Check
dataset.head()

,elevation,aspect,slope,horiz_dist_hydro,vert_dist_hydro,horiz_dist_road,hillshade_9,hill_shade_noon,hill_shade_15,horiz_dist_fire,...,soil_type_31,soil_type_32,soil_type_33,soil_type_34,soil_type_35,soil_type_36,soil_type_37,soil_type_38,soil_type_39,cover_type
0,3254,75,7,365,49,3034,228,228,133,4708,...,0,0,0,0,0,0,0,0,1,1
1,3149,341,16,216,30,3241,186,215,167,3085,...,0,0,0,0,0,0,0,0,0,1
2,2972,321,10,150,13,4796,194,230,176,4607,...,0,0,0,0,0,0,0,0,0,1
3,3097,265,21,430,60,3290,162,244,218,1503,...,0,0,0,0,0,0,0,0,0,1
4,3321,286,7,660,118,797,201,240,179,968,...,1,0,0,0,0,0,0,0,0,1

In [4]:
# Extract spearman correlations
correlations = dataset.corr(method='spearman')
# Check
correlations.head()

,elevation,aspect,slope,horiz_dist_hydro,vert_dist_hydro,horiz_dist_road,hillshade_9,hill_shade_noon,hill_shade_15,horiz_dist_fire,...,soil_type_31,soil_type_32,soil_type_33,soil_type_34,soil_type_35,soil_type_36,soil_type_37,soil_type_38,soil_type_39,cover_type
elevation,1.000000,-0.021561,-0.303318,0.390600,0.093270,0.612038,0.033711,0.196988,0.076228,0.515641,...,0.179738,0.127060,0.035709,0.122839,0.023740,0.068242,0.316250,0.306687,0.273532,0.005964
aspect,-0.021561,1.000000,0.052950,0.035934,0.082622,0.050690,-0.422601,0.395174,0.624856,-0.078669,...,0.017624,0.026647,0.011218,-0.013796,0.005640,-0.040888,0.036171,-0.039465,-0.015537,-0.004468
slope,-0.303318,0.052950,1.000000,0.014776,0.329456,-0.285127,-0.014798,-0.539812,-0.285962,-0.247467,...,-0.158421,0.087425,-0.034103,-0.045481,-0.000663,0.005219,-0.160337,0.064179,-0.031297,0.100043
horiz_dist_hydro,0.390600,0.035934,0.014776,1.000000,0.685072,0.138380,-0.041215,0.028722,0.044961,0.187558,...,0.143513,0.062571,0.051320,-0.016032,0.024601,-0.013528,0.080739,0.084976,0.189615,-0.037749
vert_dist_hydro,0.093270,0.082622,0.329456,0.685072,1.000000,-0.041321,-0.054805,-0.147636,-0.026433,-0.005881,...,0.042023,0.079472,0.017666,-0.029269,0.012898,-0.021563,-0.034885,0.064478,0.143825,0.054186

In [ ]:
# Selection rate (the x% greater correlations)
rates = [40, 50, 60]
# Select attributes based on the computed correlations
for rate in rates:
    pass