# k-Nearest Neighbors Classifier (k-NN)

The k-NN is one of the simplest classifiers in Machine Learning. Differently from other common supervised techniques, it does not perform a **learning**; instead, the algorithm checks the distance between the instance that will be classified and other feature vectors from the dataset. Due to its simplicity, it is often used in benchmarks of complex classifiers, like Artificial Neural Network (**ANN**) and Suport Vector Machine (**SVM**).

This notebook shows how the dimensionality reduction algorithms required for this work affects the 
accuracy of the k-NN classifier in the classification task posed by the Covertype dataset. Sections
are organized as follows: first, we import all necessary libraries to run k-NN from the
`sklearn` library and load the dataset, separating data from targets; then we load the results
datasets and define a function to perform k-NN over them, running also cross-validation
to validate the results; finally we compare the performance of the classifier according
to each reduced or extracted set of attributes.

## Implementation

### Import libraries 
Let's first import the libraries, mainly `pandas`, `numpy` and k-NN implementation from `sklearn`:

In [ ]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
import random

### Load results datasets

Now, load the original dataset, taking the targets apart from the features:

In [2]:
# Original dataset
dataset = pd.read_csv('datasets/new_dataset_covertype.csv')
dataset.head()
# Targets
target = dataset.iloc[:,-1]
# Dataset without classes
data = dataset.iloc[:,:-1]
data.head()

,elevation,aspect,slope,horiz_dist_hydro,vert_dist_hydro,horiz_dist_road,hillshade_9,hill_shade_noon,hill_shade_15,horiz_dist_fire,...,soil_type_30,soil_type_31,soil_type_32,soil_type_33,soil_type_34,soil_type_35,soil_type_36,soil_type_37,soil_type_38,soil_type_39
0,3254,75,7,365,49,3034,228,228,133,4708,...,0,0,0,0,0,0,0,0,0,1
1,3149,341,16,216,30,3241,186,215,167,3085,...,0,0,0,0,0,0,0,0,0,0
2,2972,321,10,150,13,4796,194,230,176,4607,...,0,0,0,0,0,0,0,0,0,0
3,3097,265,21,430,60,3290,162,244,218,1503,...,0,0,0,0,0,0,0,0,0,0
4,3321,286,7,660,118,797,201,240,179,968,...,0,1,0,0,0,0,0,0,0,0

Now, load the dataset with the results from the **genetic** algorithm executions:

In [3]:
# Read selected attributes of GA
ga  = pd.read_csv('results/genetic_algorithm.csv')

# GA dataset info
print('---------------- Genetic Algorithm ----------------')
print("Shape: ", ga.shape)
print("First Data:\n", ga.iloc[0])

---------------- Genetic Algorithm ----------------
Shape:  (2430, 59)
First Data:
 population             25
max_generations        50
combination_prob      0.7
mutation_prob        0.05
iteration               1
elevation           False
aspect              False
slope               False
horiz_dist_hydro    False
vert_dist_hydro     False
horiz_dist_road     False
hillshade_9         False
hill_shade_noon      True
hill_shade_15       False
horiz_dist_fire     False
wild_area_0          True
wild_area_1          True
wild_area_2          True
wild_area_3         False
soil_type_0         False
soil_type_1         False
soil_type_2         False
soil_type_3          True
soil_type_4         False
soil_type_5         False
soil_type_6         False
soil_type_7         False
soil_type_8          True
soil_type_9          True
soil_type_10        False
soil_type_11        False
soil_type_12        False
soil_type_13        False
soil_type_14        False
soil_type_15        False
soil_type_16        False
soil_type_17        False
soil_type_18        False
soil_type_19        False
soil_type_20        False
soil_type_21         True
soil_type_22         True
soil_type_23        False
soil_type_24        False
soil_type_25        False
soil_type_26        False
soil_type_27        False
soil_type_28         True
soil_type_29        False
soil_type_30        False
soil_type_31         True
soil_type_32        False
soil_type_33         True
soil_type_34        False
soil_type_35        False
soil_type_36        False
soil_type_37         True
soil_type_38         True
soil_type_39         True
Name: 0, dtype: object

Now, load the dataset with the results from the **PSO** algorithm executions:

In [4]:
# Read selected Attributes of PSO
pso = pd.read_csv('results/pso_selected_attributes.csv')

# PSO dataset info
print('---------------- Particle Swarm Optimization ----------------')
print("Shape: ", pso.shape)
print("First Data:\n", pso.iloc[0])

---------------- Particle Swarm Optimization ----------------
Shape:  (270, 57)
First Data:
 swarm_size                25
max_iterations            50
fitness             0.897974
elevation              False
aspect                  True
slope                  False
horiz_dist_hydro        True
vert_dist_hydro         True
horiz_dist_road         True
hillshade_9             True
hill_shade_noon         True
hill_shade_15          False
horiz_dist_fire        False
wild_area_0             True
wild_area_1             True
wild_area_2             True
wild_area_3             True
soil_type_0            False
soil_type_1             True
soil_type_2            False
soil_type_3            False
soil_type_4            False
soil_type_5             True
soil_type_6            False
soil_type_7            False
soil_type_8             True
soil_type_9             True
soil_type_10           False
soil_type_11            True
soil_type_12           False
soil_type_13           False
soil_type_14           False
soil_type_15           False
soil_type_16           False
soil_type_17           False
soil_type_18           False
soil_type_19           False
soil_type_20           False
soil_type_21            True
soil_type_22            True
soil_type_23            True
soil_type_24           False
soil_type_25            True
soil_type_26           False
soil_type_27           False
soil_type_28            True
soil_type_29           False
soil_type_30            True
soil_type_31            True
soil_type_32            True
soil_type_33           False
soil_type_34           False
soil_type_35            True
soil_type_36           False
soil_type_37            True
soil_type_38            True
soil_type_39            True
Name: 0, dtype: object

### k-NN classifier definition

In [5]:
# Defining K's
ks = [7,10,15,20,25]
acc_list = ['k7','k10','k15','k20','k25']

def perform_knn(data, attr):
    '''
    Performs knn for a given dataset.
    '''
    columns = attr.columns.tolist()[:-54] + acc_list
    new_df = pd.DataFrame(columns=columns)
    
    for index in range(len(attr)):
        vector = attr.iloc[index,-54:].tolist()
        sliced_data = data.iloc[:, vector]
        
        # Perform knn
        r = []
        for k in ks:
            knn = KNeighborsClassifier(n_neighbors=k)
            score = cross_val_score(knn, sliced_data, target, cv=10)
            r.append(score.mean())
        
        new_df.loc[index] = attr.iloc[0,:-54].tolist() + r
    
    return new_df

### k-NN execution

In [6]:
# Perform knn for the original dataset
knn_original = pd.DataFrame(columns=(['n_attr', 'accuracy', 'ks']))
index = 0
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    score = cross_val_score(knn, data, target, cv=10)
    knn_original.loc[index] = [54, score.mean(), k]
    index += 1

# Perform knn for PSO
knn_pso_result = perform_knn(data, pso)

# Perform knn for GA
knn_ga_result = perform_knn(data, ga)

# Store results
knn_pso_result.to_csv('results/knn_pso.csv')
knn_ga_result.to_csv('results/knn_ga.csv')

## Comparative results

Before comparing, we need to load the results for each algorithm:

In [7]:
# PSO results
knn_pso = pd.read_csv('results/knn_pso.csv')
# GA results
knn_ga = pd.read_csv('results/knn_ga.csv')

### Original Dataset

For the original dataset, we've got **81.69%** of accuracy:

In [8]:
knn_original.style

   n_attr  accuracy    ks
0    54.0  0.816998   7.0
1    54.0  0.803062  10.0
2    54.0  0.783195  15.0
3    54.0  0.768581  20.0
4    54.0  0.758130  25.0

### Particle Swarm Optimization

For the dataset with the attributes selected by the PSO algorithm, we've got **81.21%** of accuracy:

In [9]:
def get_n_selected(data, index):
    row = data.loc[index]
    return row.iloc[-54:].tolist().count(True)

pso_columns = ['id','n_attr'] + ['swarm_size', 'max_iterations', 'accuracy', 'ks']
pso_best_results = pd.DataFrame(columns=pso_columns)

index = 0
for i in knn_pso.columns.tolist()[-5:]:
    row = knn_pso.loc[knn_pso[i].idxmax()]
    pso_best_results.loc[index] = [int(row['Unnamed: 0']), 
                                   get_n_selected(pso, int(row['Unnamed: 0'])), 
                                   row['swarm_size'], row['max_iterations'], row[i], i]
    index += 1
    
pso_best_results.style

### Genetic Algorithm

For the dataset with the attributes selected by the genetic algorithm, we've got **73.86%** of accuracy:

In [10]:
ga_columns = ['id', 'n_attr'] + ga.columns.tolist()[:4] + ['accuracy', 'ks']
ga_best_results = pd.DataFrame(columns=ga_columns)

index = 0
for i in knn_ga.columns.tolist()[-5:]:
    row = knn_ga.loc[knn_ga[i].idxmax()]
    ga_best_results.loc[index] = [int(row['Unnamed: 0']), 
                                  get_n_selected(ga, 
                                                 int(row['Unnamed: 0']))] +\
    row.loc[ga.columns.tolist()[:4]].tolist() + [ row[i], i ]
    index += 1
    
ga_best_results.style

## Selected attributes of best results

Having the best results, we now show the selected attributes by each algorithm, using the following function:

In [11]:
def selected_attr(data, best_results):
    '''
    Having the best results for each algorithm, print
    the selected attributes.
    '''
    s = data.iloc[best_results.iloc[0,0],-54:]
    return [ s.index[i] for i in range(len(s)) if s[i] == True]

### PSO

In [12]:
print('Size:', pso_best_results.iloc[0,1], \
      '& Attrs:', selected_attr(pso, pso_best_results))

Size: 33 & Attrs: ['elevation', 'aspect', 'slope', 'horiz_dist_hydro', 'horiz_dist_road', 'hillshade_9', 'hill_shade_noon', 'horiz_dist_fire', 'wild_area_0', 'wild_area_1', 'wild_area_2', 'soil_type_0', 'soil_type_2', 'soil_type_4', 'soil_type_8', 'soil_type_9', 'soil_type_10', 'soil_type_11', 'soil_type_12', 'soil_type_15', 'soil_type_16', 'soil_type_19', 'soil_type_21', 'soil_type_23', 'soil_type_24', 'soil_type_30', 'soil_type_31', 'soil_type_32', 'soil_type_34', 'soil_type_35', 'soil_type_36', 'soil_type_37', 'soil_type_38']

### GA

In [13]:
print('Size:', ga_best_results.iloc[0,1], \
      '& Attrs:', selected_attr(ga, ga_best_results))

Size: 13 & Attrs: ['elevation', 'horiz_dist_road', 'horiz_dist_fire', 'wild_area_0', 'wild_area_2', 'soil_type_19', 'soil_type_21', 'soil_type_22', 'soil_type_28', 'soil_type_31', 'soil_type_37', 'soil_type_38', 'soil_type_39']